version: "2"

run:
  tests: true
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - unused
    - misspell
    - unconvert
    - gosec
    - bodyclose
    - errname
    - nilerr
    - nolintlint
    - predeclared
    - whitespace
  disable:
    # Disabled low-priority linters to reduce noise
    - goconst      # Repeated strings - low priority
    - gocyclo      # Cyclomatic complexity - would require refactoring
    - prealloc     # Slice preallocation - micro-optimization
    - revive       # Code style issues - low priority
    - staticcheck  # Switch statement suggestions - low priority

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false

    govet:
      enable:
        - shadow
      disable:
        - fieldalignment

    gocyclo:
      min-complexity: 15

    gosec:
      severity: medium
      confidence: medium

    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unreachable-code
        - name: redefines-builtin-id

    goconst:
      min-len: 3
      min-occurrences: 3

  exclusions:
    rules:
      - path: '_test\.go'
        linters:
          - gocyclo
          - errcheck
          - gosec
          - goconst

      - path: 'api/proto/'
        linters:
          - all

    generated: lax

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    gofmt:
      simplify: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    text:
      path: stdout
      colors: true
      print-issued-lines: true
      print-linter-name: true
  show-stats: true
