// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: api/proto/daemon.proto

package daemonv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DaemonService_Initialize_FullMethodName   = "/iperf.daemon.v1.DaemonService/Initialize"
	DaemonService_PrepareTest_FullMethodName  = "/iperf.daemon.v1.DaemonService/PrepareTest"
	DaemonService_StartServers_FullMethodName = "/iperf.daemon.v1.DaemonService/StartServers"
	DaemonService_StartClients_FullMethodName = "/iperf.daemon.v1.DaemonService/StartClients"
	DaemonService_StopAll_FullMethodName      = "/iperf.daemon.v1.DaemonService/StopAll"
	DaemonService_GetResults_FullMethodName   = "/iperf.daemon.v1.DaemonService/GetResults"
	DaemonService_GetStatus_FullMethodName    = "/iperf.daemon.v1.DaemonService/GetStatus"
)

// DaemonServiceClient is the client API for DaemonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DaemonService is the main gRPC service for the iperf daemon
type DaemonServiceClient interface {
	// Initialize prepares the daemon with configuration
	Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*InitializeResponse, error)
	// PrepareTest validates if the daemon can handle the test topology
	PrepareTest(ctx context.Context, in *PrepareTestRequest, opts ...grpc.CallOption) (*PrepareTestResponse, error)
	// StartServers starts iperf3 servers on allocated ports
	StartServers(ctx context.Context, in *StartServersRequest, opts ...grpc.CallOption) (*StartServersResponse, error)
	// StartClients starts iperf3 clients to connect to targets
	StartClients(ctx context.Context, in *StartClientsRequest, opts ...grpc.CallOption) (*StartClientsResponse, error)
	// StopAll stops all running iperf3 processes
	StopAll(ctx context.Context, in *StopAllRequest, opts ...grpc.CallOption) (*StopAllResponse, error)
	// GetResults retrieves test results from completed runs
	GetResults(ctx context.Context, in *GetResultsRequest, opts ...grpc.CallOption) (*GetResultsResponse, error)
	// GetStatus returns current daemon health and resource usage
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
}

type daemonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDaemonServiceClient(cc grpc.ClientConnInterface) DaemonServiceClient {
	return &daemonServiceClient{cc}
}

func (c *daemonServiceClient) Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*InitializeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitializeResponse)
	err := c.cc.Invoke(ctx, DaemonService_Initialize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) PrepareTest(ctx context.Context, in *PrepareTestRequest, opts ...grpc.CallOption) (*PrepareTestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareTestResponse)
	err := c.cc.Invoke(ctx, DaemonService_PrepareTest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) StartServers(ctx context.Context, in *StartServersRequest, opts ...grpc.CallOption) (*StartServersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartServersResponse)
	err := c.cc.Invoke(ctx, DaemonService_StartServers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) StartClients(ctx context.Context, in *StartClientsRequest, opts ...grpc.CallOption) (*StartClientsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartClientsResponse)
	err := c.cc.Invoke(ctx, DaemonService_StartClients_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) StopAll(ctx context.Context, in *StopAllRequest, opts ...grpc.CallOption) (*StopAllResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopAllResponse)
	err := c.cc.Invoke(ctx, DaemonService_StopAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetResults(ctx context.Context, in *GetResultsRequest, opts ...grpc.CallOption) (*GetResultsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResultsResponse)
	err := c.cc.Invoke(ctx, DaemonService_GetResults_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, DaemonService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DaemonServiceServer is the server API for DaemonService service.
// All implementations must embed UnimplementedDaemonServiceServer
// for forward compatibility.
//
// DaemonService is the main gRPC service for the iperf daemon
type DaemonServiceServer interface {
	// Initialize prepares the daemon with configuration
	Initialize(context.Context, *InitializeRequest) (*InitializeResponse, error)
	// PrepareTest validates if the daemon can handle the test topology
	PrepareTest(context.Context, *PrepareTestRequest) (*PrepareTestResponse, error)
	// StartServers starts iperf3 servers on allocated ports
	StartServers(context.Context, *StartServersRequest) (*StartServersResponse, error)
	// StartClients starts iperf3 clients to connect to targets
	StartClients(context.Context, *StartClientsRequest) (*StartClientsResponse, error)
	// StopAll stops all running iperf3 processes
	StopAll(context.Context, *StopAllRequest) (*StopAllResponse, error)
	// GetResults retrieves test results from completed runs
	GetResults(context.Context, *GetResultsRequest) (*GetResultsResponse, error)
	// GetStatus returns current daemon health and resource usage
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	mustEmbedUnimplementedDaemonServiceServer()
}

// UnimplementedDaemonServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDaemonServiceServer struct{}

func (UnimplementedDaemonServiceServer) Initialize(context.Context, *InitializeRequest) (*InitializeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Initialize not implemented")
}
func (UnimplementedDaemonServiceServer) PrepareTest(context.Context, *PrepareTestRequest) (*PrepareTestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareTest not implemented")
}
func (UnimplementedDaemonServiceServer) StartServers(context.Context, *StartServersRequest) (*StartServersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartServers not implemented")
}
func (UnimplementedDaemonServiceServer) StartClients(context.Context, *StartClientsRequest) (*StartClientsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartClients not implemented")
}
func (UnimplementedDaemonServiceServer) StopAll(context.Context, *StopAllRequest) (*StopAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopAll not implemented")
}
func (UnimplementedDaemonServiceServer) GetResults(context.Context, *GetResultsRequest) (*GetResultsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetResults not implemented")
}
func (UnimplementedDaemonServiceServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedDaemonServiceServer) mustEmbedUnimplementedDaemonServiceServer() {}
func (UnimplementedDaemonServiceServer) testEmbeddedByValue()                       {}

// UnsafeDaemonServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DaemonServiceServer will
// result in compilation errors.
type UnsafeDaemonServiceServer interface {
	mustEmbedUnimplementedDaemonServiceServer()
}

func RegisterDaemonServiceServer(s grpc.ServiceRegistrar, srv DaemonServiceServer) {
	// If the following call pancis, it indicates UnimplementedDaemonServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DaemonService_ServiceDesc, srv)
}

func _DaemonService_Initialize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitializeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).Initialize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_Initialize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).Initialize(ctx, req.(*InitializeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_PrepareTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareTestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).PrepareTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_PrepareTest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).PrepareTest(ctx, req.(*PrepareTestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_StartServers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartServersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).StartServers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_StartServers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).StartServers(ctx, req.(*StartServersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_StartClients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartClientsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).StartClients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_StartClients_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).StartClients(ctx, req.(*StartClientsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_StopAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).StopAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_StopAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).StopAll(ctx, req.(*StopAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResultsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetResults_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetResults(ctx, req.(*GetResultsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DaemonService_ServiceDesc is the grpc.ServiceDesc for DaemonService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DaemonService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "iperf.daemon.v1.DaemonService",
	HandlerType: (*DaemonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Initialize",
			Handler:    _DaemonService_Initialize_Handler,
		},
		{
			MethodName: "PrepareTest",
			Handler:    _DaemonService_PrepareTest_Handler,
		},
		{
			MethodName: "StartServers",
			Handler:    _DaemonService_StartServers_Handler,
		},
		{
			MethodName: "StartClients",
			Handler:    _DaemonService_StartClients_Handler,
		},
		{
			MethodName: "StopAll",
			Handler:    _DaemonService_StopAll_Handler,
		},
		{
			MethodName: "GetResults",
			Handler:    _DaemonService_GetResults_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _DaemonService_GetStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/daemon.proto",
}
