// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/proto/daemon.proto

package daemonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Protocol represents the transport protocol for iperf3 tests
type Protocol int32

const (
	Protocol_PROTOCOL_UNSPECIFIED Protocol = 0
	Protocol_PROTOCOL_TCP         Protocol = 1
	Protocol_PROTOCOL_UDP         Protocol = 2
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0: "PROTOCOL_UNSPECIFIED",
		1: "PROTOCOL_TCP",
		2: "PROTOCOL_UDP",
	}
	Protocol_value = map[string]int32{
		"PROTOCOL_UNSPECIFIED": 0,
		"PROTOCOL_TCP":         1,
		"PROTOCOL_UDP":         2,
	}
)

func (x Protocol) Enum() *Protocol {
	p := new(Protocol)
	*p = x
	return p
}

func (x Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_daemon_proto_enumTypes[0].Descriptor()
}

func (Protocol) Type() protoreflect.EnumType {
	return &file_api_proto_daemon_proto_enumTypes[0]
}

func (x Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol.Descriptor instead.
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_daemon_proto_rawDescGZIP(), []int{0}
}

// TestStatus represents the current state of a test
type TestStatus int32

const (
	TestStatus_TEST_STATUS_UNSPECIFIED TestStatus = 0
	TestStatus_TEST_STATUS_PENDING     TestStatus = 1
	TestStatus_TEST_STATUS_RUNNING     TestStatus = 2
	TestStatus_TEST_STATUS_COMPLETED   TestStatus = 3
	TestStatus_TEST_STATUS_FAILED      TestStatus = 4
)

// Enum value maps for TestStatus.
var (
	TestStatus_name = map[int32]string{
		0: "TEST_STATUS_UNSPECIFIED",
		1: "TEST_STATUS_PENDING",
		2: "TEST_STATUS_RUNNING",
		3: "TEST_STATUS_COMPLETED",
		4: "TEST_STATUS_FAILED",
	}
	TestStatus_value = map[string]int32{
		"TEST_STATUS_UNSPECIFIED": 0,
		"TEST_STATUS_PENDING":     1,
		"TEST_STATUS_RUNNING":     2,
		"TEST_STATUS_COMPLETED":   3,
		"TEST_STATUS_FAILED":      4,
	}
)

func (x TestStatus) Enum() *TestStatus {
	p := new(TestStatus)
	*p = x
	return p
}

func (x TestStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TestStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_daemon_proto_enumTypes[1].Descriptor()
}

func (TestStatus) Type() protoreflect.EnumType {
	return &file_api_proto_daemon_proto_enumTypes[1]
}

func (x TestStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TestStatus.Descriptor instead.
func (TestStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_daemon_proto_rawDescGZIP(), []int{1}
}

// ProcessCapacity represents the daemon's ability to run processes
type ProcessCapacity struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	MaxProcesses         int32                  `protobuf:"varint,1,opt,name=max_processes,json=maxProcesses,proto3" json:"max_processes,omitempty"`
	AvailableProcesses   int32                  `protobuf:"varint,2,opt,name=available_processes,json=availableProcesses,proto3" json:"available_processes,omitempty"`
	CpuCores             int32                  `protobuf:"varint,3,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	AvailableMemoryBytes int64                  `protobuf:"varint,4,opt,name=available_memory_bytes,json=availableMemoryBytes,proto3" json:"available_memory_bytes,omitempty"`
	NetworkInterfaces    []string               `protobuf:"bytes,5,rep,name=network_interfaces,json=networkInterfaces,proto3" json:"network_interfaces,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ProcessCapacity) Reset() {
	*x = ProcessCapacity{}
	mi := &file_api_proto_daemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessCapacity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessCapacity) ProtoMessage() {}

func (x *ProcessCapacity) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_daemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessCapacity.ProtoReflect.Descriptor instead.
func (*ProcessCapacity) Descriptor() ([]byte, []int) {
	return file_api_proto_daemon_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessCapacity) GetMaxProcesses() int32 {
	if x != nil {
		return x.MaxProcesses
	}
	return 0
}

func (x *ProcessCapacity) GetAvailableProcesses() int32 {
	if x != nil {
		return x.AvailableProcesses
	}
	return 0
}

func (x *ProcessCapacity) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *ProcessCapacity) GetAvailableMemoryBytes() int64 {
	if x != nil {
		return x.AvailableMemoryBytes
	}
	return 0
}

func (x *ProcessCapacity) GetNetworkInterfaces() []string {
	if x != nil {
		return x.NetworkInterfaces
	}
	return nil
}

// NodeInfo represents information about a node in the cluster
type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Ip            string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Capacity      *ProcessCapacity       `protobuf:"bytes,5,opt,name=capacity,proto3" json:"capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_api_proto_daemon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_daemon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_daemon_proto_rawDescGZIP(), []int{1}
}

func (x *NodeInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *NodeInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *NodeInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *NodeInfo) GetCapacity() *ProcessCapacity {
	if x != nil {
		return x.Capacity
	}
	return nil
}

// TestProfile contains all iperf3 parameters for a test
type TestProfile struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DurationSeconds   int32                  `protobuf:"varint,2,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	Protocol          Protocol               `protobuf:"varint,3,opt,name=protocol,proto3,enum=iperf.daemon.v1.Protocol" json:"protocol,omitempty"` // TCP or UDP
	Bandwidth         string                 `protobuf:"bytes,4,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`                              // e.g., "10G", "100M", "0" for unlimited
	WindowSize        string                 `protobuf:"bytes,5,opt,name=window_size,json=windowSize,proto3" json:"window_size,omitempty"`          // e.g., "416K"
	ParallelStreams   int32                  `protobuf:"varint,6,opt,name=parallel_streams,json=parallelStreams,proto3" json:"parallel_streams,omitempty"`
	Bidirectional     bool                   `protobuf:"varint,7,opt,name=bidirectional,proto3" json:"bidirectional,omitempty"`
	Reverse           bool                   `protobuf:"varint,8,opt,name=reverse,proto3" json:"reverse,omitempty"`
	BufferLength      int32                  `protobuf:"varint,9,opt,name=buffer_length,json=bufferLength,proto3" json:"buffer_length,omitempty"`
	CongestionControl string                 `protobuf:"bytes,10,opt,name=congestion_control,json=congestionControl,proto3" json:"congestion_control,omitempty"` // e.g., "cubic", "bbr" (TCP only)
	Mss               int32                  `protobuf:"varint,11,opt,name=mss,proto3" json:"mss,omitempty"`                                                     // Maximum segment size (TCP only)
	NoDelay           bool                   `protobuf:"varint,12,opt,name=no_delay,json=noDelay,proto3" json:"no_delay,omitempty"`                              // TCP no delay (TCP only)
	Tos               int32                  `protobuf:"varint,13,opt,name=tos,proto3" json:"tos,omitempty"`                                                     // Type of service
	Zerocopy          bool                   `protobuf:"varint,14,opt,name=zerocopy,proto3" json:"zerocopy,omitempty"`
	OmitSeconds       int32                  `protobuf:"varint,15,opt,name=omit_seconds,json=omitSeconds,proto3" json:"omit_seconds,omitempty"`                                                                       // Seconds to omit at start
	JsonOutput        string                 `protobuf:"bytes,16,opt,name=json_output,json=jsonOutput,proto3" json:"json_output,omitempty"`                                                                           // JSON output mode
	ExtraFlags        map[string]string      `protobuf:"bytes,17,rep,name=extra_flags,json=extraFlags,proto3" json:"extra_flags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional iperf3 flags
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TestProfile) Reset() {
	*x = TestProfile{}
	mi := &file_api_proto_daemon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestProfile) ProtoMessage() {}

func (x *TestProfile) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_daemon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestProfile.ProtoReflect.Descriptor instead.
func (*TestProfile) Descriptor() ([]byte, []int) {
	return file_api_proto_daemon_proto_rawDescGZIP(), []int{2}
}

func (x *TestProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TestProfile) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *TestProfile) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

func (x *TestProfile) GetBandwidth() string {
	if x != nil {
		return x.Bandwidth
	}
	return ""
}

func (x *TestProfile) GetWindowSize() string {
	if x != nil {
		return x.WindowSize
	}
	return ""
}

func (x *TestProfile) GetParallelStreams() int32 {
	if x != nil {
		return x.ParallelStreams
	}
	return 0
}

func (x *TestProfile) GetBidirectional() bool {
	if x != nil {
		return x.Bidirectional
	}
	return false
}

func (x *TestProfile) GetReverse() bool {
	if x != nil {
		return x.Reverse
	}
	return false
}

func (x *TestProfile) GetBufferLength() int32 {
	if x != nil {
		return x.BufferLength
	}
	return 0
}

func (x *TestProfile) GetCongestionControl() string {
	if x != nil {
		return x.CongestionControl
	}
	return ""
}

func (x *TestProfile) GetMss() int32 {
	if x != nil {
		return x.Mss
	}
	return 0
}

func (x *TestProfile) GetNoDelay() bool {
	if x != nil {
		return x.NoDelay
	}
	return false
}

func (x *TestProfile) GetTos() int32 {
	if x != nil {
		return x.Tos
	}
	return 0
}

func (x *TestProfile) GetZerocopy() bool {
	if x != nil {
		return x.Zerocopy
	}
	return false
}

func (x *TestProfile) GetOmitSeconds() int32 {
	if x != nil {
		return x.OmitSeconds
	}
	return 0
}

func (x *TestProfile) GetJsonOutput() string {
	if x != nil {
		return x.JsonOutput
	}
	return ""
}

func (x *TestProfile) GetExtraFlags() map[string]string {
	if x != nil {
		return x.ExtraFlags
	}
	return nil
}

// TestPair represents a source-destination pair for testing
type TestPair struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SourceId        string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	DestinationId   string                 `protobuf:"bytes,2,opt,name=destination_id,json=destinationId,proto3" json:"destination_id,omitempty"`
	DestinationIp   string                 `protobuf:"bytes,3,opt,name=destination_ip,json=destinationIp,proto3" json:"destination_ip,omitempty"`
	DestinationPort int32                  `protobuf:"varint,4,opt,name=destination_port,json=destinationPort,proto3" json:"destination_port,omitempty"`
	Profile         *TestProfile           `protobuf:"bytes,5,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TestPair) Reset() {
	*x = TestPair{}
	mi := &file_api_proto_daemon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestPair) ProtoMessage() {}

func (x *TestPair) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_daemon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestPair.ProtoReflect.Descriptor instead.
func (*TestPair) Descriptor() ([]byte, []int) {
	return file_api_proto_daemon_proto_rawDescGZIP(), []int{3}
}

func (x *TestPair) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *TestPair) GetDestinationId() string {
	if x != nil {
		return x.DestinationId
	}
	return ""
}

func (x *TestPair) GetDestinationIp() string {
	if x != nil {
		return x.DestinationIp
	}
	return ""
}

func (x *TestPair) GetDestinationPort() int32 {
	if x != nil {
		return x.DestinationPort
	}
	return 0
}

func (x *TestPair) GetProfile() *TestProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

// TestTopology contains all test pairs for a node
type TestTopology struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServerAssignments []*TestPair            `protobuf:"bytes,1,rep,name=server_assignments,json=serverAssignments,proto3" json:"server_assignments,omitempty"` // Tests where this node is server
	ClientAssignments []*TestPair            `protobuf:"bytes,2,rep,name=client_assignments,json=clientAssignments,proto3" json:"client_assignments,omitempty"` // Tests where this node is client
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TestTopology) Reset() {
	*x = TestTopology{}
	mi := &file_api_proto_daemon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestTopology) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestTopology) ProtoMessage() {}

func (x *TestTopology) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_daemon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestTopology.ProtoReflect.Descriptor instead.
func (*TestTopology) Descriptor() ([]byte, []int) {
	return file_api_proto_daemon_proto_rawDescGZIP(), []int{4}
}

func (x *TestTopology) GetServerAssignments() []*TestPair {
	if x != nil {
		return x.ServerAssignments
	}
	return nil
}

func (x *TestTopology) GetClientAssignments() []*TestPair {
	if x != nil {
		return x.ClientAssignments
	}
	return nil
}

// TestResult contains the output from an iperf3 run
type TestResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestId        string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	SourceId      string                 `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	DestinationId string                 `protobuf:"bytes,3,opt,name=destination_id,json=destinationId,proto3" json:"destination_id,omitempty"`
	Status        TestStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=iperf.daemon.v1.TestStatus" json:"status,omitempty"`
	IperfJson     string                 `protobuf:"bytes,5,opt,name=iperf_json,json=iperfJson,proto3" json:"iperf_json,omitempty"` // Raw iperf3 JSON output
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	StartTimeUnix int64                  `protobuf:"varint,7,opt,name=start_time_unix,json=startTimeUnix,proto3" json:"start_time_unix,omitempty"`
	EndTimeUnix   int64                  `protobuf:"varint,8,opt,name=end_time_unix,json=endTimeUnix,proto3" json:"end_time_unix,omitempty"`
	ExitCode      int32                  `protobuf:"varint,9,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestResult) Reset() {
	*x = TestResult{}
	mi := &file_api_proto_daemon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestResult) ProtoMessage() {}

func (x *TestResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_daemon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestResult.ProtoReflect.Descriptor instead.
func (*TestResult) Descriptor() ([]byte, []int) {
	return file_api_proto_daemon_proto_rawDescGZIP(), []int{5}
}

func (x *TestResult) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *TestResult) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *TestResult) GetDestinationId() string {
	if x != nil {
		return x.DestinationId
	}
	return ""
}

func (x *TestResult) GetStatus() TestStatus {
	if x != nil {
		return x.Status
	}
	return TestStatus_TEST_STATUS_UNSPECIFIED
}

func (x *TestResult) GetIperfJson() string {
	if x != nil {
		return x.IperfJson
	}
	return ""
}

func (x *TestResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TestResult) GetStartTimeUnix() int64 {
	if x != nil {
		return x.StartTimeUnix
	}
	return 0
}

func (x *TestResult) GetEndTimeUnix() int64 {
	if x != nil {
		return x.EndTimeUnix
	}
	return 0
}

func (x *TestResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

// DaemonStatus represents daemon health and resource usage
type DaemonStatus struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Healthy          bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	RunningProcesses int32                  `protobuf:"varint,2,opt,name=running_processes,json=runningProcesses,proto3" json:"running_processes,omitempty"`
	CompletedTests   int32                  `protobuf:"varint,3,opt,name=completed_tests,json=completedTests,proto3" json:"completed_tests,omitempty"`
	FailedTests      int32                  `protobuf:"varint,4,opt,name=failed_tests,json=failedTests,proto3" json:"failed_tests,omitempty"`
	CurrentCapacity  *ProcessCapacity       `protobuf:"bytes,5,opt,name=current_capacity,json=currentCapacity,proto3" json:"current_capacity,omitempty"`
	UptimeSeconds    int64                  `protobuf:"varint,6,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	Version          string                 `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DaemonStatus) Reset() {
	*x = DaemonStatus{}
	mi := &file_api_proto_daemon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonStatus) ProtoMessage() {}

func (x *DaemonStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_daemon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonStatus.ProtoReflect.Descriptor instead.
func (*DaemonStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_daemon_proto_rawDescGZIP(), []int{6}
}

func (x *DaemonStatus) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *DaemonStatus) GetRunningProcesses() int32 {
	if x != nil {
		return x.RunningProcesses
	}
	return 0
}

func (x *DaemonStatus) GetCompletedTests() int32 {
	if x != nil {
		return x.CompletedTests
	}
	return 0
}

func (x *DaemonStatus) GetFailedTests() int32 {
	if x != nil {
		return x.FailedTests
	}
	return 0
}

func (x *DaemonStatus) GetCurrentCapacity() *ProcessCapacity {
	if x != nil {
		return x.CurrentCapacity
	}
	return nil
}

func (x *DaemonStatus) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *DaemonStatus) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type InitializeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PortRangeStart int32                  `protobuf:"varint,1,opt,name=port_range_start,json=portRangeStart,proto3" json:"port_range_start,omitempty"`
	PortRangeEnd   int32                  `protobuf:"varint,2,opt,name=port_range_end,json=portRangeEnd,proto3" json:"port_range_end,omitempty"`
	MaxProcesses   int32                  `protobuf:"varint,3,opt,name=max_processes,json=maxProcesses,proto3" json:"max_processes,omitempty"`
	CpuAffinity    bool                   `protobuf:"varint,4,opt,name=cpu_affinity,json=cpuAffinity,proto3" json:"cpu_affinity,omitempty"`
	LogLevel       string                 `protobuf:"bytes,5,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	ResultDir      string                 `protobuf:"bytes,6,opt,name=result_dir,json=resultDir,proto3" json:"result_dir,omitempty"`
	SaveResults    bool                   `protobuf:"varint,7,opt,name=save_results,json=saveResults,proto3" json:"save_results,omitempty"` // Whether to save results to timestamped files
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InitializeRequest) Reset() {
	*x = InitializeRequest{}
	mi := &file_api_proto_daemon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeRequest) ProtoMessage() {}

func (x *InitializeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_daemon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeRequest.ProtoReflect.Descriptor instead.
func (*InitializeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_daemon_proto_rawDescGZIP(), []int{7}
}

func (x *InitializeRequest) GetPortRangeStart() int32 {
	if x != nil {
		return x.PortRangeStart
	}
	return 0
}

func (x *InitializeRequest) GetPortRangeEnd() int32 {
	if x != nil {
		return x.PortRangeEnd
	}
	return 0
}

func (x *InitializeRequest) GetMaxProcesses() int32 {
	if x != nil {
		return x.MaxProcesses
	}
	return 0
}

func (x *InitializeRequest) GetCpuAffinity() bool {
	if x != nil {
		return x.CpuAffinity
	}
	return false
}

func (x *InitializeRequest) GetLogLevel() string {
	if x != nil {
		return x.LogLevel
	}
	return ""
}

func (x *InitializeRequest) GetResultDir() string {
	if x != nil {
		return x.ResultDir
	}
	return ""
}

func (x *InitializeRequest) GetSaveResults() bool {
	if x != nil {
		return x.SaveResults
	}
	return false
}

type InitializeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	NodeInfo      *NodeInfo              `protobuf:"bytes,3,opt,name=node_info,json=nodeInfo,proto3" json:"node_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeResponse) Reset() {
	*x = InitializeResponse{}
	mi := &file_api_proto_daemon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeResponse) ProtoMessage() {}

func (x *InitializeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_daemon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeResponse.ProtoReflect.Descriptor instead.
func (*InitializeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_daemon_proto_rawDescGZIP(), []int{8}
}

func (x *InitializeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InitializeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InitializeResponse) GetNodeInfo() *NodeInfo {
	if x != nil {
		return x.NodeInfo
	}
	return nil
}

type PrepareTestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topology      *TestTopology          `protobuf:"bytes,1,opt,name=topology,proto3" json:"topology,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareTestRequest) Reset() {
	*x = PrepareTestRequest{}
	mi := &file_api_proto_daemon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareTestRequest) ProtoMessage() {}

func (x *PrepareTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_daemon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareTestRequest.ProtoReflect.Descriptor instead.
func (*PrepareTestRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_daemon_proto_rawDescGZIP(), []int{9}
}

func (x *PrepareTestRequest) GetTopology() *TestTopology {
	if x != nil {
		return x.Topology
	}
	return nil
}

type PrepareTestResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CanHandle         bool                   `protobuf:"varint,1,opt,name=can_handle,json=canHandle,proto3" json:"can_handle,omitempty"`
	Message           string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RequiredCapacity  *ProcessCapacity       `protobuf:"bytes,3,opt,name=required_capacity,json=requiredCapacity,proto3" json:"required_capacity,omitempty"`
	AvailableCapacity *ProcessCapacity       `protobuf:"bytes,4,opt,name=available_capacity,json=availableCapacity,proto3" json:"available_capacity,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PrepareTestResponse) Reset() {
	*x = PrepareTestResponse{}
	mi := &file_api_proto_daemon_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareTestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareTestResponse) ProtoMessage() {}

func (x *PrepareTestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_daemon_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareTestResponse.ProtoReflect.Descriptor instead.
func (*PrepareTestResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_daemon_proto_rawDescGZIP(), []int{10}
}

func (x *PrepareTestResponse) GetCanHandle() bool {
	if x != nil {
		return x.CanHandle
	}
	return false
}

func (x *PrepareTestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PrepareTestResponse) GetRequiredCapacity() *ProcessCapacity {
	if x != nil {
		return x.RequiredCapacity
	}
	return nil
}

func (x *PrepareTestResponse) GetAvailableCapacity() *ProcessCapacity {
	if x != nil {
		return x.AvailableCapacity
	}
	return nil
}

type StartServersRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ports          []int32                `protobuf:"varint,1,rep,packed,name=ports,proto3" json:"ports,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StartServersRequest) Reset() {
	*x = StartServersRequest{}
	mi := &file_api_proto_daemon_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartServersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartServersRequest) ProtoMessage() {}

func (x *StartServersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_daemon_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartServersRequest.ProtoReflect.Descriptor instead.
func (*StartServersRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_daemon_proto_rawDescGZIP(), []int{11}
}

func (x *StartServersRequest) GetPorts() []int32 {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *StartServersRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type StartServersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	StartedPorts  []int32                `protobuf:"varint,3,rep,packed,name=started_ports,json=startedPorts,proto3" json:"started_ports,omitempty"`
	Errors        []string               `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartServersResponse) Reset() {
	*x = StartServersResponse{}
	mi := &file_api_proto_daemon_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartServersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartServersResponse) ProtoMessage() {}

func (x *StartServersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_daemon_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartServersResponse.ProtoReflect.Descriptor instead.
func (*StartServersResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_daemon_proto_rawDescGZIP(), []int{12}
}

func (x *StartServersResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartServersResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StartServersResponse) GetStartedPorts() []int32 {
	if x != nil {
		return x.StartedPorts
	}
	return nil
}

func (x *StartServersResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type ClientTarget struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TestId          string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	DestinationIp   string                 `protobuf:"bytes,2,opt,name=destination_ip,json=destinationIp,proto3" json:"destination_ip,omitempty"`
	DestinationPort int32                  `protobuf:"varint,3,opt,name=destination_port,json=destinationPort,proto3" json:"destination_port,omitempty"`
	Profile         *TestProfile           `protobuf:"bytes,4,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ClientTarget) Reset() {
	*x = ClientTarget{}
	mi := &file_api_proto_daemon_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientTarget) ProtoMessage() {}

func (x *ClientTarget) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_daemon_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientTarget.ProtoReflect.Descriptor instead.
func (*ClientTarget) Descriptor() ([]byte, []int) {
	return file_api_proto_daemon_proto_rawDescGZIP(), []int{13}
}

func (x *ClientTarget) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *ClientTarget) GetDestinationIp() string {
	if x != nil {
		return x.DestinationIp
	}
	return ""
}

func (x *ClientTarget) GetDestinationPort() int32 {
	if x != nil {
		return x.DestinationPort
	}
	return 0
}

func (x *ClientTarget) GetProfile() *TestProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type StartClientsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Targets       []*ClientTarget        `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartClientsRequest) Reset() {
	*x = StartClientsRequest{}
	mi := &file_api_proto_daemon_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartClientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartClientsRequest) ProtoMessage() {}

func (x *StartClientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_daemon_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartClientsRequest.ProtoReflect.Descriptor instead.
func (*StartClientsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_daemon_proto_rawDescGZIP(), []int{14}
}

func (x *StartClientsRequest) GetTargets() []*ClientTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

type StartClientsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	StartedTestIds []string               `protobuf:"bytes,3,rep,name=started_test_ids,json=startedTestIds,proto3" json:"started_test_ids,omitempty"`
	Errors         []string               `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StartClientsResponse) Reset() {
	*x = StartClientsResponse{}
	mi := &file_api_proto_daemon_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartClientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartClientsResponse) ProtoMessage() {}

func (x *StartClientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_daemon_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartClientsResponse.ProtoReflect.Descriptor instead.
func (*StartClientsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_daemon_proto_rawDescGZIP(), []int{15}
}

func (x *StartClientsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartClientsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StartClientsResponse) GetStartedTestIds() []string {
	if x != nil {
		return x.StartedTestIds
	}
	return nil
}

func (x *StartClientsResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type StopAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Force         bool                   `protobuf:"varint,1,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopAllRequest) Reset() {
	*x = StopAllRequest{}
	mi := &file_api_proto_daemon_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopAllRequest) ProtoMessage() {}

func (x *StopAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_daemon_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopAllRequest.ProtoReflect.Descriptor instead.
func (*StopAllRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_daemon_proto_rawDescGZIP(), []int{16}
}

func (x *StopAllRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type StopAllResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message          string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	StoppedProcesses int32                  `protobuf:"varint,3,opt,name=stopped_processes,json=stoppedProcesses,proto3" json:"stopped_processes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StopAllResponse) Reset() {
	*x = StopAllResponse{}
	mi := &file_api_proto_daemon_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopAllResponse) ProtoMessage() {}

func (x *StopAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_daemon_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopAllResponse.ProtoReflect.Descriptor instead.
func (*StopAllResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_daemon_proto_rawDescGZIP(), []int{17}
}

func (x *StopAllResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopAllResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StopAllResponse) GetStoppedProcesses() int32 {
	if x != nil {
		return x.StoppedProcesses
	}
	return 0
}

type GetResultsRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TestIds             []string               `protobuf:"bytes,1,rep,name=test_ids,json=testIds,proto3" json:"test_ids,omitempty"` // Empty means all results
	ClearAfterRetrieval bool                   `protobuf:"varint,2,opt,name=clear_after_retrieval,json=clearAfterRetrieval,proto3" json:"clear_after_retrieval,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetResultsRequest) Reset() {
	*x = GetResultsRequest{}
	mi := &file_api_proto_daemon_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResultsRequest) ProtoMessage() {}

func (x *GetResultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_daemon_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResultsRequest.ProtoReflect.Descriptor instead.
func (*GetResultsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_daemon_proto_rawDescGZIP(), []int{18}
}

func (x *GetResultsRequest) GetTestIds() []string {
	if x != nil {
		return x.TestIds
	}
	return nil
}

func (x *GetResultsRequest) GetClearAfterRetrieval() bool {
	if x != nil {
		return x.ClearAfterRetrieval
	}
	return false
}

type GetResultsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*TestResult          `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResultsResponse) Reset() {
	*x = GetResultsResponse{}
	mi := &file_api_proto_daemon_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResultsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResultsResponse) ProtoMessage() {}

func (x *GetResultsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_daemon_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResultsResponse.ProtoReflect.Descriptor instead.
func (*GetResultsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_daemon_proto_rawDescGZIP(), []int{19}
}

func (x *GetResultsResponse) GetResults() []*TestResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *GetResultsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_api_proto_daemon_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_daemon_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_daemon_proto_rawDescGZIP(), []int{20}
}

type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *DaemonStatus          `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_api_proto_daemon_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_daemon_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_daemon_proto_rawDescGZIP(), []int{21}
}

func (x *GetStatusResponse) GetStatus() *DaemonStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_api_proto_daemon_proto protoreflect.FileDescriptor

const file_api_proto_daemon_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/daemon.proto\x12\x0fiperf.daemon.v1\"\xe9\x01\n" +
	"\x0fProcessCapacity\x12#\n" +
	"\rmax_processes\x18\x01 \x01(\x05R\fmaxProcesses\x12/\n" +
	"\x13available_processes\x18\x02 \x01(\x05R\x12availableProcesses\x12\x1b\n" +
	"\tcpu_cores\x18\x03 \x01(\x05R\bcpuCores\x124\n" +
	"\x16available_memory_bytes\x18\x04 \x01(\x03R\x14availableMemoryBytes\x12-\n" +
	"\x12network_interfaces\x18\x05 \x03(\tR\x11networkInterfaces\"\x98\x01\n" +
	"\bNodeInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12<\n" +
	"\bcapacity\x18\x05 \x01(\v2 .iperf.daemon.v1.ProcessCapacityR\bcapacity\"\xae\x05\n" +
	"\vTestProfile\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12)\n" +
	"\x10duration_seconds\x18\x02 \x01(\x05R\x0fdurationSeconds\x125\n" +
	"\bprotocol\x18\x03 \x01(\x0e2\x19.iperf.daemon.v1.ProtocolR\bprotocol\x12\x1c\n" +
	"\tbandwidth\x18\x04 \x01(\tR\tbandwidth\x12\x1f\n" +
	"\vwindow_size\x18\x05 \x01(\tR\n" +
	"windowSize\x12)\n" +
	"\x10parallel_streams\x18\x06 \x01(\x05R\x0fparallelStreams\x12$\n" +
	"\rbidirectional\x18\a \x01(\bR\rbidirectional\x12\x18\n" +
	"\areverse\x18\b \x01(\bR\areverse\x12#\n" +
	"\rbuffer_length\x18\t \x01(\x05R\fbufferLength\x12-\n" +
	"\x12congestion_control\x18\n" +
	" \x01(\tR\x11congestionControl\x12\x10\n" +
	"\x03mss\x18\v \x01(\x05R\x03mss\x12\x19\n" +
	"\bno_delay\x18\f \x01(\bR\anoDelay\x12\x10\n" +
	"\x03tos\x18\r \x01(\x05R\x03tos\x12\x1a\n" +
	"\bzerocopy\x18\x0e \x01(\bR\bzerocopy\x12!\n" +
	"\fomit_seconds\x18\x0f \x01(\x05R\vomitSeconds\x12\x1f\n" +
	"\vjson_output\x18\x10 \x01(\tR\n" +
	"jsonOutput\x12M\n" +
	"\vextra_flags\x18\x11 \x03(\v2,.iperf.daemon.v1.TestProfile.ExtraFlagsEntryR\n" +
	"extraFlags\x1a=\n" +
	"\x0fExtraFlagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd8\x01\n" +
	"\bTestPair\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12%\n" +
	"\x0edestination_id\x18\x02 \x01(\tR\rdestinationId\x12%\n" +
	"\x0edestination_ip\x18\x03 \x01(\tR\rdestinationIp\x12)\n" +
	"\x10destination_port\x18\x04 \x01(\x05R\x0fdestinationPort\x126\n" +
	"\aprofile\x18\x05 \x01(\v2\x1c.iperf.daemon.v1.TestProfileR\aprofile\"\xa2\x01\n" +
	"\fTestTopology\x12H\n" +
	"\x12server_assignments\x18\x01 \x03(\v2\x19.iperf.daemon.v1.TestPairR\x11serverAssignments\x12H\n" +
	"\x12client_assignments\x18\x02 \x03(\v2\x19.iperf.daemon.v1.TestPairR\x11clientAssignments\"\xcb\x02\n" +
	"\n" +
	"TestResult\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\tR\bsourceId\x12%\n" +
	"\x0edestination_id\x18\x03 \x01(\tR\rdestinationId\x123\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1b.iperf.daemon.v1.TestStatusR\x06status\x12\x1d\n" +
	"\n" +
	"iperf_json\x18\x05 \x01(\tR\tiperfJson\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x12&\n" +
	"\x0fstart_time_unix\x18\a \x01(\x03R\rstartTimeUnix\x12\"\n" +
	"\rend_time_unix\x18\b \x01(\x03R\vendTimeUnix\x12\x1b\n" +
	"\texit_code\x18\t \x01(\x05R\bexitCode\"\xaf\x02\n" +
	"\fDaemonStatus\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12+\n" +
	"\x11running_processes\x18\x02 \x01(\x05R\x10runningProcesses\x12'\n" +
	"\x0fcompleted_tests\x18\x03 \x01(\x05R\x0ecompletedTests\x12!\n" +
	"\ffailed_tests\x18\x04 \x01(\x05R\vfailedTests\x12K\n" +
	"\x10current_capacity\x18\x05 \x01(\v2 .iperf.daemon.v1.ProcessCapacityR\x0fcurrentCapacity\x12%\n" +
	"\x0euptime_seconds\x18\x06 \x01(\x03R\ruptimeSeconds\x12\x18\n" +
	"\aversion\x18\a \x01(\tR\aversion\"\x8a\x02\n" +
	"\x11InitializeRequest\x12(\n" +
	"\x10port_range_start\x18\x01 \x01(\x05R\x0eportRangeStart\x12$\n" +
	"\x0eport_range_end\x18\x02 \x01(\x05R\fportRangeEnd\x12#\n" +
	"\rmax_processes\x18\x03 \x01(\x05R\fmaxProcesses\x12!\n" +
	"\fcpu_affinity\x18\x04 \x01(\bR\vcpuAffinity\x12\x1b\n" +
	"\tlog_level\x18\x05 \x01(\tR\blogLevel\x12\x1d\n" +
	"\n" +
	"result_dir\x18\x06 \x01(\tR\tresultDir\x12!\n" +
	"\fsave_results\x18\a \x01(\bR\vsaveResults\"\x80\x01\n" +
	"\x12InitializeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x126\n" +
	"\tnode_info\x18\x03 \x01(\v2\x19.iperf.daemon.v1.NodeInfoR\bnodeInfo\"O\n" +
	"\x12PrepareTestRequest\x129\n" +
	"\btopology\x18\x01 \x01(\v2\x1d.iperf.daemon.v1.TestTopologyR\btopology\"\xee\x01\n" +
	"\x13PrepareTestResponse\x12\x1d\n" +
	"\n" +
	"can_handle\x18\x01 \x01(\bR\tcanHandle\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12M\n" +
	"\x11required_capacity\x18\x03 \x01(\v2 .iperf.daemon.v1.ProcessCapacityR\x10requiredCapacity\x12O\n" +
	"\x12available_capacity\x18\x04 \x01(\v2 .iperf.daemon.v1.ProcessCapacityR\x11availableCapacity\"T\n" +
	"\x13StartServersRequest\x12\x14\n" +
	"\x05ports\x18\x01 \x03(\x05R\x05ports\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\x05R\x0etimeoutSeconds\"\x87\x01\n" +
	"\x14StartServersResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rstarted_ports\x18\x03 \x03(\x05R\fstartedPorts\x12\x16\n" +
	"\x06errors\x18\x04 \x03(\tR\x06errors\"\xb1\x01\n" +
	"\fClientTarget\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\x12%\n" +
	"\x0edestination_ip\x18\x02 \x01(\tR\rdestinationIp\x12)\n" +
	"\x10destination_port\x18\x03 \x01(\x05R\x0fdestinationPort\x126\n" +
	"\aprofile\x18\x04 \x01(\v2\x1c.iperf.daemon.v1.TestProfileR\aprofile\"N\n" +
	"\x13StartClientsRequest\x127\n" +
	"\atargets\x18\x01 \x03(\v2\x1d.iperf.daemon.v1.ClientTargetR\atargets\"\x8c\x01\n" +
	"\x14StartClientsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\x10started_test_ids\x18\x03 \x03(\tR\x0estartedTestIds\x12\x16\n" +
	"\x06errors\x18\x04 \x03(\tR\x06errors\"&\n" +
	"\x0eStopAllRequest\x12\x14\n" +
	"\x05force\x18\x01 \x01(\bR\x05force\"r\n" +
	"\x0fStopAllResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x11stopped_processes\x18\x03 \x01(\x05R\x10stoppedProcesses\"b\n" +
	"\x11GetResultsRequest\x12\x19\n" +
	"\btest_ids\x18\x01 \x03(\tR\atestIds\x122\n" +
	"\x15clear_after_retrieval\x18\x02 \x01(\bR\x13clearAfterRetrieval\"l\n" +
	"\x12GetResultsResponse\x125\n" +
	"\aresults\x18\x01 \x03(\v2\x1b.iperf.daemon.v1.TestResultR\aresults\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\x12\n" +
	"\x10GetStatusRequest\"J\n" +
	"\x11GetStatusResponse\x125\n" +
	"\x06status\x18\x01 \x01(\v2\x1d.iperf.daemon.v1.DaemonStatusR\x06status*H\n" +
	"\bProtocol\x12\x18\n" +
	"\x14PROTOCOL_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPROTOCOL_TCP\x10\x01\x12\x10\n" +
	"\fPROTOCOL_UDP\x10\x02*\x8e\x01\n" +
	"\n" +
	"TestStatus\x12\x1b\n" +
	"\x17TEST_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TEST_STATUS_PENDING\x10\x01\x12\x17\n" +
	"\x13TEST_STATUS_RUNNING\x10\x02\x12\x19\n" +
	"\x15TEST_STATUS_COMPLETED\x10\x03\x12\x16\n" +
	"\x12TEST_STATUS_FAILED\x10\x042\xf3\x04\n" +
	"\rDaemonService\x12U\n" +
	"\n" +
	"Initialize\x12\".iperf.daemon.v1.InitializeRequest\x1a#.iperf.daemon.v1.InitializeResponse\x12X\n" +
	"\vPrepareTest\x12#.iperf.daemon.v1.PrepareTestRequest\x1a$.iperf.daemon.v1.PrepareTestResponse\x12[\n" +
	"\fStartServers\x12$.iperf.daemon.v1.StartServersRequest\x1a%.iperf.daemon.v1.StartServersResponse\x12[\n" +
	"\fStartClients\x12$.iperf.daemon.v1.StartClientsRequest\x1a%.iperf.daemon.v1.StartClientsResponse\x12L\n" +
	"\aStopAll\x12\x1f.iperf.daemon.v1.StopAllRequest\x1a .iperf.daemon.v1.StopAllResponse\x12U\n" +
	"\n" +
	"GetResults\x12\".iperf.daemon.v1.GetResultsRequest\x1a#.iperf.daemon.v1.GetResultsResponse\x12R\n" +
	"\tGetStatus\x12!.iperf.daemon.v1.GetStatusRequest\x1a\".iperf.daemon.v1.GetStatusResponseB;Z9github.com/bensons/iperf-cnc/api/proto/daemon/v1;daemonv1b\x06proto3"

var (
	file_api_proto_daemon_proto_rawDescOnce sync.Once
	file_api_proto_daemon_proto_rawDescData []byte
)

func file_api_proto_daemon_proto_rawDescGZIP() []byte {
	file_api_proto_daemon_proto_rawDescOnce.Do(func() {
		file_api_proto_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_daemon_proto_rawDesc), len(file_api_proto_daemon_proto_rawDesc)))
	})
	return file_api_proto_daemon_proto_rawDescData
}

var file_api_proto_daemon_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_api_proto_daemon_proto_goTypes = []any{
	(Protocol)(0),                // 0: iperf.daemon.v1.Protocol
	(TestStatus)(0),              // 1: iperf.daemon.v1.TestStatus
	(*ProcessCapacity)(nil),      // 2: iperf.daemon.v1.ProcessCapacity
	(*NodeInfo)(nil),             // 3: iperf.daemon.v1.NodeInfo
	(*TestProfile)(nil),          // 4: iperf.daemon.v1.TestProfile
	(*TestPair)(nil),             // 5: iperf.daemon.v1.TestPair
	(*TestTopology)(nil),         // 6: iperf.daemon.v1.TestTopology
	(*TestResult)(nil),           // 7: iperf.daemon.v1.TestResult
	(*DaemonStatus)(nil),         // 8: iperf.daemon.v1.DaemonStatus
	(*InitializeRequest)(nil),    // 9: iperf.daemon.v1.InitializeRequest
	(*InitializeResponse)(nil),   // 10: iperf.daemon.v1.InitializeResponse
	(*PrepareTestRequest)(nil),   // 11: iperf.daemon.v1.PrepareTestRequest
	(*PrepareTestResponse)(nil),  // 12: iperf.daemon.v1.PrepareTestResponse
	(*StartServersRequest)(nil),  // 13: iperf.daemon.v1.StartServersRequest
	(*StartServersResponse)(nil), // 14: iperf.daemon.v1.StartServersResponse
	(*ClientTarget)(nil),         // 15: iperf.daemon.v1.ClientTarget
	(*StartClientsRequest)(nil),  // 16: iperf.daemon.v1.StartClientsRequest
	(*StartClientsResponse)(nil), // 17: iperf.daemon.v1.StartClientsResponse
	(*StopAllRequest)(nil),       // 18: iperf.daemon.v1.StopAllRequest
	(*StopAllResponse)(nil),      // 19: iperf.daemon.v1.StopAllResponse
	(*GetResultsRequest)(nil),    // 20: iperf.daemon.v1.GetResultsRequest
	(*GetResultsResponse)(nil),   // 21: iperf.daemon.v1.GetResultsResponse
	(*GetStatusRequest)(nil),     // 22: iperf.daemon.v1.GetStatusRequest
	(*GetStatusResponse)(nil),    // 23: iperf.daemon.v1.GetStatusResponse
	nil,                          // 24: iperf.daemon.v1.TestProfile.ExtraFlagsEntry
}
var file_api_proto_daemon_proto_depIdxs = []int32{
	2,  // 0: iperf.daemon.v1.NodeInfo.capacity:type_name -> iperf.daemon.v1.ProcessCapacity
	0,  // 1: iperf.daemon.v1.TestProfile.protocol:type_name -> iperf.daemon.v1.Protocol
	24, // 2: iperf.daemon.v1.TestProfile.extra_flags:type_name -> iperf.daemon.v1.TestProfile.ExtraFlagsEntry
	4,  // 3: iperf.daemon.v1.TestPair.profile:type_name -> iperf.daemon.v1.TestProfile
	5,  // 4: iperf.daemon.v1.TestTopology.server_assignments:type_name -> iperf.daemon.v1.TestPair
	5,  // 5: iperf.daemon.v1.TestTopology.client_assignments:type_name -> iperf.daemon.v1.TestPair
	1,  // 6: iperf.daemon.v1.TestResult.status:type_name -> iperf.daemon.v1.TestStatus
	2,  // 7: iperf.daemon.v1.DaemonStatus.current_capacity:type_name -> iperf.daemon.v1.ProcessCapacity
	3,  // 8: iperf.daemon.v1.InitializeResponse.node_info:type_name -> iperf.daemon.v1.NodeInfo
	6,  // 9: iperf.daemon.v1.PrepareTestRequest.topology:type_name -> iperf.daemon.v1.TestTopology
	2,  // 10: iperf.daemon.v1.PrepareTestResponse.required_capacity:type_name -> iperf.daemon.v1.ProcessCapacity
	2,  // 11: iperf.daemon.v1.PrepareTestResponse.available_capacity:type_name -> iperf.daemon.v1.ProcessCapacity
	4,  // 12: iperf.daemon.v1.ClientTarget.profile:type_name -> iperf.daemon.v1.TestProfile
	15, // 13: iperf.daemon.v1.StartClientsRequest.targets:type_name -> iperf.daemon.v1.ClientTarget
	7,  // 14: iperf.daemon.v1.GetResultsResponse.results:type_name -> iperf.daemon.v1.TestResult
	8,  // 15: iperf.daemon.v1.GetStatusResponse.status:type_name -> iperf.daemon.v1.DaemonStatus
	9,  // 16: iperf.daemon.v1.DaemonService.Initialize:input_type -> iperf.daemon.v1.InitializeRequest
	11, // 17: iperf.daemon.v1.DaemonService.PrepareTest:input_type -> iperf.daemon.v1.PrepareTestRequest
	13, // 18: iperf.daemon.v1.DaemonService.StartServers:input_type -> iperf.daemon.v1.StartServersRequest
	16, // 19: iperf.daemon.v1.DaemonService.StartClients:input_type -> iperf.daemon.v1.StartClientsRequest
	18, // 20: iperf.daemon.v1.DaemonService.StopAll:input_type -> iperf.daemon.v1.StopAllRequest
	20, // 21: iperf.daemon.v1.DaemonService.GetResults:input_type -> iperf.daemon.v1.GetResultsRequest
	22, // 22: iperf.daemon.v1.DaemonService.GetStatus:input_type -> iperf.daemon.v1.GetStatusRequest
	10, // 23: iperf.daemon.v1.DaemonService.Initialize:output_type -> iperf.daemon.v1.InitializeResponse
	12, // 24: iperf.daemon.v1.DaemonService.PrepareTest:output_type -> iperf.daemon.v1.PrepareTestResponse
	14, // 25: iperf.daemon.v1.DaemonService.StartServers:output_type -> iperf.daemon.v1.StartServersResponse
	17, // 26: iperf.daemon.v1.DaemonService.StartClients:output_type -> iperf.daemon.v1.StartClientsResponse
	19, // 27: iperf.daemon.v1.DaemonService.StopAll:output_type -> iperf.daemon.v1.StopAllResponse
	21, // 28: iperf.daemon.v1.DaemonService.GetResults:output_type -> iperf.daemon.v1.GetResultsResponse
	23, // 29: iperf.daemon.v1.DaemonService.GetStatus:output_type -> iperf.daemon.v1.GetStatusResponse
	23, // [23:30] is the sub-list for method output_type
	16, // [16:23] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_api_proto_daemon_proto_init() }
func file_api_proto_daemon_proto_init() {
	if File_api_proto_daemon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_daemon_proto_rawDesc), len(file_api_proto_daemon_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_daemon_proto_goTypes,
		DependencyIndexes: file_api_proto_daemon_proto_depIdxs,
		EnumInfos:         file_api_proto_daemon_proto_enumTypes,
		MessageInfos:      file_api_proto_daemon_proto_msgTypes,
	}.Build()
	File_api_proto_daemon_proto = out.File
	file_api_proto_daemon_proto_goTypes = nil
	file_api_proto_daemon_proto_depIdxs = nil
}
